# Generated by Django 6.0 on 2025-12-15 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('endedeco', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id_especie', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'especie',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('funcao', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'funcionario',
            },
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id_raca', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'raca',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id_servico', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'servico',
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id_agendamento', models.AutoField(primary_key=True, serialize=False)),
                ('data_agendamento', models.DateField()),
                ('hora', models.TimeField()),
                ('descricao', models.CharField(blank=True, max_length=45, null=True)),
                ('funcionario', models.ForeignKey(db_column='id_funcionario', on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='app.funcionario')),
            ],
            options={
                'db_table': 'agendamento',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(blank=True, max_length=20, null=True)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('agendamento', models.ForeignKey(db_column='id_agendamento', on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='app.agendamento')),
            ],
            options={
                'db_table': 'pagamento',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id_pet', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='app.cliente')),
                ('especie', models.ForeignKey(db_column='id_especie', on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='app.especie')),
                ('raca', models.ForeignKey(db_column='id_raca', on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='app.raca')),
            ],
            options={
                'db_table': 'pet',
            },
        ),
        migrations.AddField(
            model_name='agendamento',
            name='pet',
            field=models.ForeignKey(db_column='id_pet', on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='app.pet'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(db_column='id_servico', on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='app.servico'),
        ),
    ]
